//
//  load-input-context.hpp
//  vulkan-renderer
//
//  Created by Kenneth Esdaile on 4/18/24.
//

#ifndef load_input_context_hpp
#define load_input_context_hpp

#define KEGE_INPUT_ACTION_ENUMS \
KEGE_INPUT_ACTION( ACTION_1 ),\
KEGE_INPUT_ACTION( ACTION_2 ),\
KEGE_INPUT_ACTION( ACTION_3 ),\
KEGE_INPUT_ACTION( ACTION_4 ),\
KEGE_INPUT_ACTION( ACTION_5 ),\
KEGE_INPUT_ACTION( ACTION_6 ),\
KEGE_INPUT_ACTION( ACTION_7 ),\
KEGE_INPUT_ACTION( ACTION_8 ),\
KEGE_INPUT_ACTION( ACTION_9 ),\
KEGE_INPUT_ACTION( ACTION_10 ),\
KEGE_INPUT_ACTION( ACTION_11 ),\
KEGE_INPUT_ACTION( ACTION_12 ),\
KEGE_INPUT_ACTION( ACTION_13 ),\
KEGE_INPUT_ACTION( ACTION_14 ),\
KEGE_INPUT_ACTION( ACTION_15 ),\
KEGE_INPUT_ACTION( ACTION_16 ),\
KEGE_INPUT_ACTION( ACTION_17 ),\
KEGE_INPUT_ACTION( ACTION_18 ),\
KEGE_INPUT_ACTION( ACTION_19 ),\
KEGE_INPUT_ACTION( ACTION_20 ),\
KEGE_INPUT_ACTION( MOVE_FORWARD ),\
KEGE_INPUT_ACTION( MOVE_BACKWARD ),\
KEGE_INPUT_ACTION( MOVE_LEFTWARD ),\
KEGE_INPUT_ACTION( MOVE_RIGHTWARD ),\
KEGE_INPUT_ACTION( MOVE_UPWARD ),\
KEGE_INPUT_ACTION( MOVE_DOWNWARD ),\
KEGE_INPUT_ACTION( LOOK_UP ),\
KEGE_INPUT_ACTION( LOOK_DOWN ),\
KEGE_INPUT_ACTION( LOOK_LEFT ),\
KEGE_INPUT_ACTION( LOOK_RIGHT ),\
KEGE_INPUT_ACTION( CONTROL_CAMERA ),\
KEGE_INPUT_ACTION( ZOOM ),\
KEGE_INPUT_ACTION( ZOOM_IN ),\
KEGE_INPUT_ACTION( ZOOM_OUT ),\
KEGE_INPUT_ACTION( JUMP ),\
KEGE_INPUT_ACTION( WALK ),\
KEGE_INPUT_ACTION( RUN ),\
\
KEGE_INPUT_ACTION( TOGGLE_WIREFRAME ),\
KEGE_INPUT_ACTION( CAMERA_CHANGE ),\
KEGE_INPUT_ACTION( AVATAR_CHANGE ),\
KEGE_INPUT_ACTION( CAST_RAY ),\
\
KEGE_INPUT_ACTION( MAX_COUNT )

#define KEGE_INPUT_ACTION(x) ACTION_##x
namespace kege
{
    enum
    {
        KEGE_INPUT_ACTION_ENUMS,
        TOTAL_ENUM_ACTIONS
    };
}
#undef KEGE_INPUT_ACTION


namespace kege{

    const char* enumActionToString( int type );
}

#endif /* load_input_context_hpp */
