//
//  shader-compiler.cpp
//  assets
//
//  Created by Kenneth Esdaile on 2/11/26.
//

//#include "graphics.hpp"
#include "shader-compiler.hpp"

namespace kege{

    void ShaderCompiler::compileVariant(const kege::PipelineKey& key)
    {
        _key = key;
        _set_index = 0;
        _binding_index = 0;
        
        writeFeatures();
        std::string vs = writeVertexShader();
        std::string fs = writeFragmentShader();
        compileShader(key, vs, fs);
    }

    void ShaderCompiler::getVariant(const kege::PipelineKey& key)
    {
        //auto it = _variant_cache.find(key);
        //if (it != _variant_cache.end())
        //    return it->second;

        // Compile new variant (expensive!)
        //Ref< kege::ShaderPipeline > variant = compileVariant(key);
        //_variant_cache[key] = variant;
        //return variant;
    }

    std::string ShaderCompiler::writeVertexShader()
    {
        std::stringstream source;
        beginVertexShader(source);

        writeVersion(source);
        writeExtensions(source);
        processInput(source);
        processOutput(source);
        processResources(source);
        writeFunctions(source);
        writeMainFn(source);

        endVertexShader(source);
        return source.str();
    }

    std::string ShaderCompiler::writeFragmentShader()
    {
        std::stringstream source;
        beginFragmentShader(source);

        writeVersion(source);
        writeExtensions(source);
        processInput(source);
        processOutput(source);
        processResources(source);
        writeFunctions(source);
        writeMainFn(source);

        endFragmentShader(source);
        return source.str();
    }

    void ShaderCompiler::compileShader(const kege::PipelineKey& key, const std::string& vs, const std::string& fs)
    {
        const std::string path = "/Users/kae/Developer/vscode/kege-engine/kege/assets/shaders/glsl/";

        // Open file for writing
        std::ofstream vsFile(path + "vs.glsl");
        // Write the entire string buffer
        vsFile << vs;
        // Close the file
        vsFile.close();


        // Open file for writing
        std::ofstream fsFile(path + "fs.glsl");
        // Write the entire string buffer
        fsFile << fs;
        // Close the file
        fsFile.close();


//        kege::ShaderPipelineDesc description;
//
//        description.shaders = std::vector< ref::Shader >
//        {
//            _graphics->createShader(kege::ShaderDesc{
//                .stage = kege::ShaderStageFlag::Vertex,
//                .byte_code = _graphics->compileGlslToSpv
//                (
//                    kege::ShaderStageFlag::Vertex,
//                    "name", vs.c_str(), vs.length()
//                ),
//                .entry_point = "main",
//                .name = "",
//            }),
//            _graphics->createShader(kege::ShaderDesc{
//                .stage = kege::ShaderStageFlag::Fragment,
//                .byte_code = _graphics->compileGlslToSpv
//                (
//                    kege::ShaderStageFlag::Fragment,
//                    "name", fs.c_str(), fs.length()
//                ),
//                .entry_point = "main",
//                .name = "",
//            }),
//        };
//
//        description.features = key.features;
//        description.depth_stencil = key.depth_state;
//        description.input_assembly.topology = key.topology;
//        description.rasterizer = key.raster_state;
//        description.vertex_layout = _vertex_layout;
//        description.pipeline_rendering = _pipeline_rendering;
//        description.shader_layout = _shader_layout;
//
//        if(key.blend_state.enable) description.color_blend.attachments.push_back(key.blend_state);
//
//        _graphics->createShaderPipeline(description);
//        return nullptr;
    }

    void ShaderCompiler::addAttribute(kege::VertexBit vertex_bit, int location, kege::ShaderVar type, const char* name )
    {
//        _vertex_layout.attributes.push_back(kege::VertexAttribute{
//            .name = name,
//            .location = uint8_t(location),
//            .binding = uint8_t(0),
//            .type = type,
//            .semantic = vertex_bit
//        });
//        _inputs.push_back({ vertex_bit, location });
    }

    void ShaderCompiler::beginVertexShader(std::stringstream& source)
    {
        source << "// Vertex Shader: automatically generated by KEGE based on pipeline key.\n\n";
        _current_stage = kege::ShaderStageFlag::Vertex;
        _curr_stage = &_stages[ _current_stage ];
    }

    void ShaderCompiler::endVertexShader(std::stringstream& source){
//        _inputs = _outputs;
//        _outputs = {};
    }

    void ShaderCompiler::beginFragmentShader(std::stringstream& source)
    {
        source << "// Fragment Shader: automatically generated by KEGE based on pipeline key.\n\n";
        _current_stage = kege::ShaderStageFlag::Fragment;
        _curr_stage = &_stages[ _current_stage ];

        _has_normal_mapping = (_key.features & kege::FeatureFlag::NORMAL_MAPPING);
        _has_material = (_key.features & kege::FeatureFlag::MATERIAL);

        _has_lights = (_key.features & kege::FeatureFlag::DIRECTIONAL_LIGHT) ||
        (_key.features & kege::FeatureFlag::POINT_LIGHT) ||
        (_key.features & kege::FeatureFlag::SPOT_LIGHT);

        _has_light_funct =
        _key.shading_model == kege::ShadingModel::LitPBR_Metallic ||
        _key.shading_model == kege::ShadingModel::LitPBR_Subsurface ||
        _key.shading_model == kege::ShadingModel::LitPBR_Clearcoat ||
        _key.shading_model == kege::ShadingModel::LitPBR_Cloth |
        _key.shading_model == kege::ShadingModel::LitPBR_Skin ||
        _key.shading_model == kege::ShadingModel::LitPBR_Hair;
    }

    void ShaderCompiler::endFragmentShader(std::stringstream& source)
    {
//        _inputs = _outputs;
//        _outputs = {};
    }

    void ShaderCompiler::writeVersion(std::stringstream& source)
    {
        source << "#version 450\n";
    }

    void ShaderCompiler::writeExtensions(std::stringstream& source)
    {
        source << "#extension GL_ARB_separate_shader_objects : enable\n\n";
    }

    void ShaderCompiler::writeResource(std::stringstream& source, const std::string& fname)
    {
        const std::string& snippet = include(fname);

        ShaderReflection sr;
        sr.parse_source( snippet );

        const std::vector<ShaderResource>& resources = sr.get_resources();
        for (const ShaderResource& res : resources)
        {
            kege::Ref< kege::ShaderStructBlock > block;
            if( !res.members.empty() )
            {
                std::vector<kege::ShaderStructField> fields;
                for (auto& mem : res.members)
                {
                    fields.push_back
                    ({
                        .count = 1,
                        .type = mem.type,
                        .name = mem.name,
                        .size = static_cast<uint32_t>( kege::sizeOf( kege::stringToShaderVarType(mem.type) ) )
                    });
                }
                block = new ShaderStructBlock(ShaderStructType::Buffer, res.struct_type, fields);
            }

            if( res.type != kege::ShaderResourceType::PushConstant )
            {
                BindPointDesc bind_point;
                bind_point.name = res.name;
                bind_point.count = 1;
                bind_point.stages |= _current_stage;
                bind_point.block = block;

                switch (res.type)
                {
                    case ShaderResourceType::UniformBuffer: bind_point.usage = kege::BindingUsage::UniformBuffer;
                        break;
                    case ShaderResourceType::StorageBuffer: bind_point.usage = kege::BindingUsage::StorageBuffer;
                        break;
                    case ShaderResourceType::StorageImage: bind_point.usage = kege::BindingUsage::StorageImage;
                        break;
                    case ShaderResourceType::SampledImage: bind_point.usage = kege::BindingUsage::SampledImage;
                        break;
                    case ShaderResourceType::Sampler: bind_point.usage = kege::BindingUsage::Sampler;
                        break;
                    default: break;
                }

                std::set<std::string> set;
                auto it = _defs.find(res.set);
                if (it == _defs.end())
                {
                    uint32_t set_index;
                    if (std::all_of(res.set.begin(), res.set.end(), ::isdigit))
                    {
                        set_index = static_cast<uint32_t>(std::stoul(res.set));
                    }
                    else
                    {
                        set_index = _set_index++;
                    }

                    define(source, res.set, set_index);
                    if (std::all_of(res.binding.begin(), res.binding.end(), ::isdigit))
                    {
                        bind_point.index = static_cast<uint32_t>(std::stoul(res.binding));
                    }
                    else
                    {
                        bind_point.index = _binding_index++;
                        define(source, res.binding, bind_point.index);
                    }

                    _defs[res.set] = {set_index, bind_point.index};

                    _shader_sets.push_back
                    ({
                        .index = set_index,
                        .name = res.block_name,
                        .bindings = {{bind_point}}
                    });
                }
                else
                {
                    if (std::all_of(res.binding.begin(), res.binding.end(), ::isdigit))
                    {
                        bind_point.index = static_cast<uint32_t>(std::stoul(res.binding));
                    }
                    else
                    {
                        define(source, res.binding, it->second.binding);
                        bind_point.index = _binding_index++;
                    }

                    if (!std::all_of(res.set.begin(), res.set.end(), ::isdigit))
                    {
                        // ensure that the set macro is defined once per shader that uses it
                        if(set.find(res.set) != set.end())
                        {
                            set.insert(res.set);
                            define(source, res.set, it->second.set);
                        }
                    }
                    _shader_sets[ it->second.set ].bindings.push_back(bind_point);
                }
            }
            else
            {
                PushBlockDesc push_block = {};
                push_block.name = res.name;
                push_block.size = res.block_size;
                push_block.count = 1;
                push_block.stages = _current_stage;
                push_block.block = block;
                _push_blocks.push_back(push_block);
            }
        }
        source << snippet;
    }

    void ShaderCompiler::writeOutputs(std::stringstream& source, const std::string& fname)
    {
        std::string snippet = include("output/" + fname);

        ShaderReflection sr;
        sr.parse_source( snippet );

        const std::vector<ShaderIO>& outputs = sr.get_outputs();
        for (const ShaderIO& io : outputs)
        {
            if (!std::all_of(io.location.begin(), io.location.end(), ::isdigit))
            {
                _curr_stage->output.push_back(io);
                define(source, io.location, _output_location);

                if(io.location.compare(0, 3, "OUT_"))
                {
                    const char* str = io.location.c_str();
                    str += 4;
                    std::string in = std::string("IN_") + str;
                    _defs[ in ].set = _output_location;
                    //define(source, std::string("IN_") + str, _output_location);
                }
                _output_location += 1;
            }
        }
        source << snippet;

        _output_fnames.push_back(fname);
    }

    void ShaderCompiler::writeInputs(std::stringstream& source, const std::string& fname)
    {
        const std::string& snippet = include("input/" + fname);

        ShaderReflection sr;
        sr.parse_source( snippet );

        const std::vector<ShaderIO>& inputs = sr.get_inputs();
        for (const ShaderIO& io : inputs)
        {
            if (!std::all_of(io.location.begin(), io.location.end(), ::isdigit))
            {
                _curr_stage->input.push_back(io);
                auto a = _defs.find(io.location);
                if(a == _defs.end())
                    define(source, io.location, _input_location++);
                else
                    define(source, io.location, a->second.set);
            }
        }
        source << snippet;
    }

    void ShaderCompiler::processInput(std::stringstream& source)
    {
        if(_current_stage == kege::ShaderStageFlag::Vertex)
        {
            switch (_key.renderer_type)
            {
                case kege::MeshType::StaticMesh:
                    writeInputs(source, "static-mesh.glsl");
                    break;

                default:
                case kege::MeshType::Point:
                    writeInputs(source, "point.glsl");
                    break;

                case kege::MeshType::ScreenRect:
                    writeInputs(source, "screen-rect.glsl");
                    break;

                case kege::MeshType::Particle:
                    writeInputs(source, "particle.glsl");
                    break;

                case kege::MeshType::FlatTerrain:
                    writeInputs(source, "flat-terrain.glsl");
                    break;

                case kege::MeshType::SphericalTerrain:
                    writeInputs(source, "spherical-terrain.glsl");
                    break;
            }

            if (_key.features & kege::FeatureFlag::NORMAL_MAPPING)
            {
                writeInputs(source, "normal-mapping.glsl");
            }
            if (_key.features & kege::FeatureFlag::GPU_SKINNING)
            {
                writeInputs(source, "gpu-skinning.glsl");
            }

            if (_key.features == kege::FeatureFlag::VERTEX_COLOR)
            {
                writeInputs(source, "vertex-color.glsl");
            }
        }
        else if(_current_stage == kege::ShaderStageFlag::Fragment)
        {
            for(const std::string& input : _output_fnames)
            {
                writeInputs(source, input);
            }
        }
        source << "\n";
    }

    void ShaderCompiler::processOutput(std::stringstream& source)
    {
        if(_current_stage == kege::ShaderStageFlag::Vertex)
        {
            switch (_key.renderer_type)
            {
                case kege::MeshType::StaticMesh:
                    writeOutputs(source, "static-mesh.glsl");
                    break;

                default:
                case kege::MeshType::Point:
                    writeOutputs(source, "point.glsl");
                    break;

                case kege::MeshType::ScreenRect:
                    writeOutputs(source, "screen-rect.glsl");
                    break;

                case kege::MeshType::Particle:
                    writeOutputs(source, "particle.glsl");
                    break;

                case kege::MeshType::FlatTerrain:
                    writeOutputs(source, "flat-terrain.glsl");
                    break;

                case kege::MeshType::SphericalTerrain:
                    writeOutputs(source, "spherical-terrain.glsl");
                    break;
            }

            if (_key.features & kege::FeatureFlag::NORMAL_MAPPING)
            {
                writeOutputs(source, "normal-mapping.glsl");
            }

            if (_key.features == kege::FeatureFlag::VERTEX_COLOR)
            {
                writeOutputs(source, "vertex-color.glsl");
            }
        }
        else if(_current_stage == kege::ShaderStageFlag::Fragment)
        {
            switch ( _key.render_pass )
            {
                default:
                {
                    writeOutputs(source, "write-color-buffer.glsl");
                    break;
                }
                case kege::RenderPass::GBuffer:
                {
                    writeOutputs(source, "write-geometry-buffer.glsl");
                    break;
                }
                case kege::RenderPass::Lighting:
                {
                    writeOutputs(source, "write-hd-color-buffer.glsl");
                    break;
                }
            }
        }
        source << "\n";
    }

    void ShaderCompiler::processResources(std::stringstream& source)
    {
        writeResource(source, "resources/uniform-camera-data.glsl");
        writeResource(source, "resources/uniform-object-data.glsl");

        if(_current_stage == kege::ShaderStageFlag::Fragment)
        {
            if ((_key.features & kege::FeatureFlag::MATERIAL))
            {
                writeResource(source, "resources/uniform-material.glsl");
            }

            if ((_key.features & kege::FeatureFlag::IMAGE_BASE_LIGHTING))
            {
                writeResource(source, "resources/textures-ibl.glsl");
            }

            if ((_key.features & kege::FeatureFlag::DIRECTIONAL_LIGHT))
            {
                writeResource(source, "resources/uniform-directional-light.glsl");
            }
            if ((_key.features & kege::FeatureFlag::POINT_LIGHT))
            {
                writeResource(source, "resources/uniform-point-light.glsl");
            }
            if ((_key.features & kege::FeatureFlag::SPOT_LIGHT))
            {
                writeResource(source, "resources/uniform-spot-light.glsl");
            }
        }
    }

    void ShaderCompiler::writeFunctions(std::stringstream& source)
    {
        if(_current_stage == kege::ShaderStageFlag::Fragment)
        {
            if( _has_material )
            {
                source << include( "resources/fn-get-albedo.glsl") <<"\n";
                if (_has_normal_mapping)
                {
                    source << include( "resources/fn-get-tbn-normal.glsl") <<"\n";
                }
            }
            if( _has_material && _has_light_funct && _has_lights )
            {
                source << include( "resources/fn-get-opacity.glsl") <<"\n";
                source << include( "resources/fn-get-ambient-occlusion.glsl") <<"\n";
                source << include( "resources/fn-get-roughness.glsl") <<"\n";
                source << include( "resources/fn-get-metallic.glsl") <<"\n";
                source << include( "resources/fn-get-albedo.glsl") <<"\n";
                source << include( "resources/fn-get-normal.glsl") <<"\n";
                source << include( "resources/fn-get-emissive.glsl") <<"\n";
            }

            if ((_key.features & kege::FeatureFlag::IMAGE_BASE_LIGHTING))
            {
                source << include( "shading-model/fn-calc-ambient-ibl.glsl") <<"\n";
            }

            if (_key.shading_model == kege::ShadingModel::LitPBR_Metallic ||
                _key.shading_model == kege::ShadingModel::LitPBR_Skin ||
                _key.shading_model == kege::ShadingModel::LitPBR_Hair ||
                _key.shading_model == kege::ShadingModel::LitPBR_Cloth ||
                _key.shading_model == kege::ShadingModel::LitPBR_Subsurface ||
                _key.shading_model == kege::ShadingModel::LitPBR_Clearcoat )
            {
                source << include( "shading-model/fn-brdf.glsl") <<"\n";
            }

            if (_key.shading_model == kege::ShadingModel::LitPBR_Metallic)
            {
                source << include( "shading-model/fn-lighting.glsl") <<"\n";
            }

            if ((_key.features & kege::FeatureFlag::IMAGE_BASE_LIGHTING))
            {
                source << include( "shading-model/fn-calc-ambient-ibl.glsl") <<"\n";
            }
            if ((_key.features & kege::FeatureFlag::MATERIAL))
            {
                source << include( "resources/fn-material.glsl") <<"\n";
                if ((_key.features & kege::FeatureFlag::NORMAL_MAPPING))
                {
                    source << include( "resources/fn-normal-mapping.glsl") <<"\n";
                }

                if ((_key.features & kege::FeatureFlag::ANISOTROPIC_REFLECTION))
                {
                    source << include( "resources/fn-anisotropy.glsl") <<"\n";
                }

                if ((_key.features & kege::FeatureFlag::CLEAR_COAT))
                {
                    source << include( "resources/fn-clear-coat.glsl") <<"\n";
                }
            }
        }
    }
    
    void ShaderCompiler::writeMainFn(std::stringstream& source)
    {
        source <<"\n";
        source << "void main() {\n";
        switch ( _current_stage )
        {
            case kege::ShaderStageFlag::Vertex:
            {
                source << "    // Process vertex based on renderer type\n";

                if (_key.renderer_type == kege::MeshType::StaticMesh && (_key.features & kege::FeatureFlag::GPU_SKINNING))
                {
                    source << include( "renderer-type/gpu-skinning.glsl") <<"\n";
                    if (_key.features & kege::FeatureFlag::NORMAL_MAPPING)
                    {
                        source << include( "renderer-type/gpu-skinning-normal-mapping.glsl") <<"\n";
                    }
                }
                else if (_key.renderer_type == kege::MeshType::StaticMesh)
                {
                    source << include( "renderer-type/static-mesh.glsl") <<"\n";
                    if (_key.features & kege::FeatureFlag::NORMAL_MAPPING)
                    {
                        source << include( "renderer-type/static-mesh-normal-mapping.glsl") <<"\n";
                    }
                }
                else if (_key.renderer_type == kege::MeshType::FlatTerrain)
                {
                }
                else if (_key.renderer_type == kege::MeshType::SphericalTerrain)
                {
                }
                else if (_key.renderer_type == kege::MeshType::Particle)
                {
                }

                if (_key.features == kege::FeatureFlag::VERTEX_COLOR)
                {
                    source << include( "main/vertex/static-color.glsl") <<"\n";
                }

                source << include( "renderer-type/final-vertex-output.glsl") <<"\n";
            }
            break;

            case kege::ShaderStageFlag::Fragment:
            {
                if(( _input_signature & VertexBit::POSITION ))
                {
                    source << "    vec3 position = in_position;\n";
                }
                if( _has_material )
                {
                    source << include( "resources/get-albedo.glsl") <<"\n";
                    if (_has_normal_mapping)
                    {
                        source << include( "resources/get-tbn-normal.glsl") <<"\n";
                    }
                }
                if( _has_light_funct )
                {
                    if( _has_material && _has_lights )
                    {
                        source << include( "resources/get-opacity.glsl") <<"\n";
                        source << include( "resources/get-ambient-occlusion.glsl") <<"\n";
                        source << include( "resources/get-roughness.glsl") <<"\n";
                        source << include( "resources/get-metallic.glsl") <<"\n";
                        source << include( "resources/get-normal.glsl") <<"\n";
                        source << include( "resources/get-emissive.glsl") <<"\n";
                    }
                    else
                    {
                        source << include( "resources/use-internal-material.glsl") <<"\n";
                        if(( _input_signature & (1 << VertexBit::NORMAL) ))
                        {
                            source << include( "resources/get-input-normal.glsl") <<"\n";
                        }
                    }
                    
                    if(( _input_signature & (1 << VertexBit::POSITION) ))
                    {
                        source << "    vec3 view_dir = normalize(camera.cameraPosition - in_position);\n";
                    }

                    if( _has_lights )
                    {
                        if ((_key.features & kege::FeatureFlag::DIRECTIONAL_LIGHT))
                        {
                            source << include( "resources/integrate-directional-light.glsl") <<"\n";
                        }
                        if ((_key.features & kege::FeatureFlag::POINT_LIGHT))
                        {
                            source << include( "resources/integrate-point-light.glsl") <<"\n\n";
                        }
                        if ((_key.features & kege::FeatureFlag::SPOT_LIGHT))
                        {
                            source << include( "resources/integrate-spot-light.glsl") <<"\n\n";
                        }
                    }
                    else
                    {
                        source << include( "resources/use-internal-light.glsl") <<"\n";
                    }
                }
                else if (_key.shading_model == kege::ShadingModel::Unlit)
                {
                    if( _has_material )
                    {
                        source << "    vec3 final_color = getAlbedo();\n";
                    }
                    if(( _input_signature & VertexBit::COLOR ))
                    {
                        source << "    vec3 final_color = in_color.rgb;\n";
                    }
                }

                if ((_key.features & kege::FeatureFlag::TONE_MAPPING))
                {
                    source << include( "features/tone-mapping.glsl") <<"\n\n";
                }
                
                if ((_key.features & kege::FeatureFlag::GAMMA))
                {
                    source << include( "features/gamma.glsl") <<"\n\n";
                }

                switch (_key.render_pass)
                {
                    default:
                    case RenderPass::Forward:
                        source << include( "render-pass/to-color-buffer.glsl") <<"\n";
                        break;

                    case RenderPass::GBuffer:
                        source << include( "render-pass/to-geometry-buffer.glsl") <<"\n";
                        break;

                    case RenderPass::Shadow:
                        source << include( "render-pass/to-depth-buffer.glsl") <<"\n";
                        break;

                    case RenderPass::DepthPrePass:
                        source << include( "render-pass/to-depth-buffer.glsl") <<"\n";
                        break;
                }
            }
            break;

            default: break;
        }
        source << "}\n";
    }

    std::string ShaderCompiler::include(const std::string& fname )
    {
        const std::string filename = "/Users/kae/Developer/vscode/kege-engine/kege/assets/shaders/glsl/snippets/" + fname;
        std::ifstream file(filename);
        std::string loaded_source((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
        file.close();
//        if(loaded_source.length() >= 1)
//        {
//            size_t i = loaded_source.length() - 1;
//            if(loaded_source[ i ] == '\n')
//                loaded_source[ i ] = ' ';
//        }
        return loaded_source;
    }

    std::string ShaderCompiler::process(const std::string& fname )
    {
        std::string source = include( fname );

        ShaderReflection refl;
        refl.parse_file( fname );

        return source;
    }

    void ShaderCompiler::processShadingModel(std::stringstream& source, const kege::ShadingModel& model)
    {
        switch(model)
        {
            default:
            case kege::ShadingModel::Unlit:
            {
                source << include("shading-model/unlit.glsl");
                break;
            }

            case kege::ShadingModel::LitPBR_Metallic:
            {
                source << include("shading-model/lit-pbr-metallic.glsl");
                break;
            }
        }
    }

    void ShaderCompiler::processMeshType(std::stringstream& source, const kege::PipelineKey& key)
    {
        switch(key.renderer_type)
        {
            default:
            case kege::MeshType::Point:
            {
                source << include("renderer-type/point.glsl");
                break;
            }
            case kege::MeshType::StaticMesh:
            {
                source << include("renderer-type/static-mesh.glsl");
                break;
            }
        }

        if (key.features & kege::FeatureFlag::NORMAL_MAPPING)
        {
            source << include("feature/vertex/normal-mapping.glsl");
        }

        if (key.features & kege::FeatureFlag::GPU_SKINNING)
        {
            source << include("feature/vertex/gpu-skinning.glsl");
        }

        if (key.features & kege::FeatureFlag::VERTEX_COLOR)
        {
            source << include("feature/vertex/vertex-color.glsl");
        }
    }

    void ShaderCompiler::define(std::stringstream& source, const std::string& name, int index)
    {
        source << "#define " << name <<" " << index << "\n";
    }

    std::string ShaderCompiler::parseDefineName(const std::string& line) {
        size_t pos = 0;

        // Skip leading whitespace
        while (pos < line.size() && std::isspace(line[pos])) pos++;

        // Must start with #define
        if (line.compare(pos, 7, "#define")!= 0) return "";
        pos += 7;

        // Skip whitespace after #define
        while (pos < line.size() && std::isspace(line[pos])) pos++;

        // Read identifier: [A-Za-z_][A-Za-z0-9_]*
        size_t start = pos;
        if (pos < line.size() && (std::isalpha(line[pos]) || line[pos] == '_')) {
            pos++;
            while (pos < line.size() && (std::isalnum(line[pos]) || line[pos] == '_')) {
                pos++;
            }
            return line.substr(start, pos - start);
        }
        return "";
    }

    void ShaderCompiler::addDefine(Defines& defines, const std::string& name, int index)
    {
        if( defines.table.find(name) != defines.table.end()) return;
        defines.table[ name ] = defines.defs.size();
        defines.defs.push_back({name, index});
    }

    void ShaderCompiler::writeFeatures()
    {
        // ====== VERTEX SHADER FEATURES ======
        if (_key.features & kege::FeatureFlag::VERTEX_ANIMATION)
            addDefine(_global_defines, "FEATURE_VERTEX_ANIMATION");
        if (_key.features & kege::FeatureFlag::MORPH_TARGETS)
            addDefine(_global_defines, "FEATURE_MORPH_TARGETS");
        if (_key.features & kege::FeatureFlag::GPU_SKINNING)
            addDefine(_global_defines, "FEATURE_GPU_SKINNING");
        if (_key.features & kege::FeatureFlag::VERTEX_DISPLACEMENT)
            addDefine(_global_defines, "FEATURE_VERTEX_DISPLACEMENT");
        if (_key.features & kege::FeatureFlag::WIND_ANIMATION)
            addDefine(_global_defines, "FEATURE_WIND_ANIMATION");
        if (_key.features & kege::FeatureFlag::VERTEX_ANIMATION)
            addDefine(_global_defines, "FEATURE_VERTEX_ANIMATION");
        if (_key.features & kege::FeatureFlag::INSTANCED_RENDERING)
            addDefine(_global_defines, "FEATURE_INSTANCED_RENDERING");
        if (_key.features & kege::FeatureFlag::VERTEX_COLOR)
            addDefine(_global_defines, "FEATURE_VERTEX_COLOR");

        // ====== TESSELLATION FEATURES ======
        if (_key.features & kege::FeatureFlag::TESSELLATION)
            addDefine(_global_defines, "FEATURE_TESSELLATION");
        if (_key.features & kege::FeatureFlag::PN_TRIANGLES)
            addDefine(_global_defines, "FEATURE_PN_TRIANGLES");
        if (_key.features & kege::FeatureFlag::TESSELLATION_DISPLACEMENT)
            addDefine(_global_defines, "FEATURE_DISPLACEMENT_TESSELLATION");

        // ====== FRAGMENT SHADER FEATURES ======
        if (_key.features & kege::FeatureFlag::NORMAL_MAPPING)
            addDefine(_global_defines, "FEATURE_NORMAL_MAPPING");
        if (_key.features & kege::FeatureFlag::TRIPLANAR_MAPPING)
            addDefine(_global_defines, "FEATURE_TRIPLANAR_MAPPING");
        if (_key.features & kege::FeatureFlag::PARALLAX_MAPPING)
            addDefine(_global_defines, "FEATURE_PARALLAX_MAPPING");
        if (_key.features & kege::FeatureFlag::PARALLAX_OCCLUSION)
            addDefine(_global_defines, "FEATURE_PARALLAX_OCCLUSION");

        // ====== MATERIAL LAYERS ======
        if (_key.features & kege::FeatureFlag::CLEAR_COAT)
            addDefine(_global_defines, "FEATURE_CLEAR_COAT");
        if (_key.features & kege::FeatureFlag::ANISOTROPIC_REFLECTION)
            addDefine(_global_defines, "FEATURE_ANISOTROPIC_REFLECTION");
        if (_key.features & kege::FeatureFlag::SHEEN_LAYER)
            addDefine(_global_defines, "FEATURE_SHEEN_LAYER");
        if (_key.features & kege::FeatureFlag::THIN_FILM)
            addDefine(_global_defines, "FEATURE_THIN_FILM");
        if (_key.features & kege::FeatureFlag::TRANSMISSION)
            addDefine(_global_defines, "FEATURE_TRANSMISSION");
        if (_key.features & kege::FeatureFlag::SUBSURFACE_SCATTERING)
            addDefine(_global_defines, "FEATURE_SUBSURFACE_SCATTERING");

        // ====== TRANSPARENCY/ALPHA ======
        if (_key.features & kege::FeatureFlag::ALPHA_TEST)
            addDefine(_global_defines, "FEATURE_ALPHA_TEST");
        if (_key.features & kege::FeatureFlag::ALPHA_TO_COVERAGE)
            addDefine(_global_defines, "FEATURE_ALPHA_TO_COVERAGE");
        if (_key.features & kege::FeatureFlag::DITHERED_OPACITY)
            addDefine(_global_defines, "FEATURE_DITHERED_OPACITY");
        if (_key.features & kege::FeatureFlag::PREMULTIPLIED_ALPHA)
            addDefine(_global_defines, "FEATURE_PREMULTIPLIED_ALPHA");

        // ====== PARTICLE EFFECTS ======
        if (_key.features & kege::FeatureFlag::SOFT_PARTICLES)
            addDefine(_global_defines, "FEATURE_ANISOTROPIC_REFLECTION");
        if (_key.features & kege::FeatureFlag::PARTICLE_ROTATION)
            addDefine(_global_defines, "FEATURE_PARTICLE_ROTATION");

        // ====== ENVIRONMENT INTERACTION ======
        if (_key.features & kege::FeatureFlag::SCREEN_SPACE_REFLECTION)
            addDefine(_global_defines, "FEATURE_ANISOTROPIC_REFLECTION");
        if (_key.features & kege::FeatureFlag::REFRACTION)
            addDefine(_global_defines, "FEATURE_ANISOTROPIC_REFLECTION");
        if (_key.features & kege::FeatureFlag::WATER_EFFECTS)
            addDefine(_global_defines, "FEATURE_ANISOTROPIC_REFLECTION");
        if (_key.features & kege::FeatureFlag::DECAL)
            addDefine(_global_defines, "FEATURE_DECAL");

        // ====== LIGHTING FEATURES ======
        if (_key.features & kege::FeatureFlag::MULTIPLE_BOUNCE_GI)
            addDefine(_global_defines, "FEATURE_MULTIPLE_BOUNCE_GI");
        if (_key.features & kege::FeatureFlag::AREA_LIGHTS)
            addDefine(_global_defines, "FEATURE_AREA_LIGHTS");
        if (_key.features & kege::FeatureFlag::CONTACT_SHADOWS)
            addDefine(_global_defines, "FEATURE_CONTACT_SHADOWS");
        if (_key.features & kege::FeatureFlag::VOLUMETRIC_LIGHTING)
            addDefine(_global_defines, "FEATURE_VOLUMETRIC_LIGHTING");


        // ====== POST-PROCESS/SCREEN SPACE ======
        if (_key.features & kege::FeatureFlag::MOTION_VECTORS)
            addDefine(_global_defines, "FEATURE_MOTION_VECTORS");
        if (_key.features & kege::FeatureFlag::VELOCITY_BUFFER)
            addDefine(_global_defines, "FEATURE_VELOCITY_BUFFER");
        if (_key.features & kege::FeatureFlag::DEPTH_ONLY)
            addDefine(_global_defines, "FEATURE_DEPTH_ONLY");
        if (_key.features & kege::FeatureFlag::CUSTOM_DEPTH)
            addDefine(_global_defines, "FEATURE_CUSTOM_DEPTH");

        // ====== TERRAIN/VEGETATION ======
        if (_key.features & kege::FeatureFlag::TERRAIN_BLENDING)
            addDefine(_global_defines, "FEATURE_TERRAIN_BLENDING");
        if (_key.features & kege::FeatureFlag::VERTEX_GRASS_WIND)
            addDefine(_global_defines, "FEATURE_VERTEX_GRASS_WIND");
        if (_key.features & kege::FeatureFlag::LOD_CROSSFADE)
            addDefine(_global_defines, "FEATURE_LOD_CROSSFADE");
        if (_key.features & kege::FeatureFlag::DECAL_LAYER)
            addDefine(_global_defines, "FEATURE_DECAL_LAYER");

        // ====== DEBUG/DEVELOPMENT ======
        if (_key.features & kege::FeatureFlag::WIREFRAME_OVERLAY)
            addDefine(_global_defines, "FEATURE_WIREFRAME_OVERLAY");
        if (_key.features & kege::FeatureFlag::DEBUG_NORMALS)
            addDefine(_global_defines, "FEATURE_DEBUG_NORMALS");
        if (_key.features & kege::FeatureFlag::DEBUG_UVS)
            addDefine(_global_defines, "FEATURE_DEBUG_UVS");
        if (_key.features & kege::FeatureFlag::DEBUG_TANGENTS)
            addDefine(_global_defines, "FEATURE_DEBUG_TANGENTS");

        // ====== SHADOW FEATURES ======
        if (_key.features & kege::FeatureFlag::CONTACT_HARDENING)
            addDefine(_global_defines, "FEATURE_CONTACT_HARDENING");
        if (_key.features & kege::FeatureFlag::VARIANCE_SHADOW_MAP)
            addDefine(_global_defines, "FEATURE_VARIANCE_SHADOW_MAP");
        if (_key.features & kege::FeatureFlag::CASCADE_BLENDING)
            addDefine(_global_defines, "FEATURE_CASCADE_BLENDING");

        // ====== ADVANCED RENDERING ======
        if (_key.features & kege::FeatureFlag::RAY_TRACING_OVERRIDE)
            addDefine(_global_defines, "FEATURE_RAY_TRACING_OVERRIDE");
        if (_key.features & kege::FeatureFlag::VIRTUAL_TEXTURE)
            addDefine(_global_defines, "FEATURE_VIRTUAL_TEXTURE");
        if (_key.features & kege::FeatureFlag::FLIPBOOK_ANIMATION)
            addDefine(_global_defines, "FEATURE_FLIPBOOK_ANIMATION");

        // ====== UI RENDERING ======
        if (_key.features & kege::FeatureFlag::ROUNDED_UI_CORNERS)
            addDefine(_global_defines, "FEATURE_ROUNDED_UI_CORNERS");
        if (_key.features & kege::FeatureFlag::SINE_DIST_TEXT)
            addDefine(_global_defines, "FEATURE_SINE_DIST_TEXT");

        // ====== FRAGMENT SHADER FEATURES ======
        if (_key.features & kege::FeatureFlag::DETAIL_NORMAL)
            addDefine(_global_defines, "FEATURE_DETAIL_NORMAL");
    }

    ShaderCompiler::ShaderCompiler(kege::Graphics* graphics)
    :   _graphics(graphics)
    {}
}
