//
//  render-pass-desc.hpp
//  runtime
//
//  Created by Kenneth Esdaile on 4/22/26.
//

#ifndef render_pass_desc_hpp
#define render_pass_desc_hpp

#include "../../../resource/asset-manager.hpp"
#include "../../render/graph/render-graph-common.hpp"
#include "../../render/render-graph-resource-manager.hpp"

namespace kege{

    struct RenderPassContext;
    // Signature for all pass record functions
    using RenderPassFunc = std::function<void(RenderPassContext&)>;

    struct RgRenderPassDesc
    {
        std::string name;
        kege::QueueType type;
        kege::RenderPassType pass;

        /**
         * Resources read/consumed by this render pass.
         * These resources are produced by previous passes.
         */
        std::vector< kege::RgReadResrcDesc > reads;

        /**
         * Resources written/produced by this render pass.
         * These resources can be used as inputs for subsequent passes.
         */
        std::vector< kege::RgWriteResrcDesc > writes;

        kege::RenderPassFunc execute;
    };
    using ActiveRenderPassDescs = std::vector< const RgRenderPassDesc* >;
    using RenderPassFrame = std::vector< ActiveRenderPassDescs >;


    // Pass context gives systems safe access to their resources
    struct RenderPassContext
    {
        uint32_t frame_index;

        // needed for binding global shader resources
        const kege::RgRenderPassDesc* pass_desc = nullptr;

        kege::ref::CommandBuffer command_buffer;
        kege::AssetManager* asset_manager;
        kege::Renderer* renderer;
        const kege::RenderView* view;
    };


    /**
     * A render pass node represents an instance of a render pass in the execution sequence. 
     * It contains the pass description, any resource barriers that need to be applied before 
     * execution, and metadata such as submit index and culling status.
     * The render graph will use these nodes to determine the order of execution, resource 
     * state transitions, and which passes can be culled based on the current render view and 
     * scene state.
     */
    struct RenderPassNode
    {
        PassId id;
        const RgRenderPassDesc* desc;

        /**
         * Barriers to apply at the start of this render pass.
         * These ensure proper resource state transitions before usage.
         * Node: Populating barriers is optional. If left empty then the barriers
         * will be automatically generated by the render graph.
         */
        BarrierDescriptions barriers;

        uint32_t submit_index;
        bool culled = true;
    };

    // A sequence of render pass nodes that defines the order of execution for a frame.
    using RenderPassNodes = std::vector< RenderPassNode >;


    /**
     * A render pass frame represents the collection of render passes that need to be executed for a single frame.
     * Each entry in the frame corresponds to a render pass and contains the active pass descriptions that should 
     * be executed for that pass. The render graph will build this frame based on the render views and
     * the dependencies between passes, and then compile it into an execution plan.
     */
    struct RenderGraphFrame
    {
        kege::RenderPassFrame render_pass_frame;
        const kege::RenderViewFrame* render_view_frame = nullptr;
    };


    struct RenderPassExecutionSequence
    {
        RenderPassNodes nodes;
        std::vector< SubmitDesc > submits;
    };

    struct RenderFrameExecution
    {
        kege::RenderPassExecutionSequence execution_sequence;
        kege::Ref< kege::RenderView > render_view;
    };
    
    using RenderGraphExecutionPlan = std::vector< RenderFrameExecution >;




    struct RenderGraphDescriptor
    {
        const kege::RgRenderPassDesc* findPass( const std::string& name )
        {
            auto i = pass_name_index_table.find( name );
            return (i != pass_name_index_table.end())? &passes[ i->second ] : nullptr;
        }
        const kege::RgRenderPassDesc* getPassByType( RenderPassType type )
        {
            auto i = pass_type_index_table.find( type );
            return (i != pass_type_index_table.end())? &passes[ i->second ] : nullptr;
        }
        const kege::RgRenderPassDesc* getPassByIndex( uint32_t index )
        {
            return (index < passes.size())? &passes[ index ] : nullptr;
        }

        const kege::RgSamplerDesc* findSampler( const std::string& name )const
        {
            auto i = sampler_lookup_table.find( name );
            return (i != sampler_lookup_table.end())? &samplers[ i->second ] : nullptr;
        }
        kege::RgSamplerDesc* findSampler( const std::string& name )
        {
            auto i = sampler_lookup_table.find( name );
            return (i != sampler_lookup_table.end())? &samplers[ i->second ] : nullptr;
        }

        const kege::RgBufferDesc* findBuffer( const std::string& name )const
        {
            auto i = buffer_lookup_table.find( name );
            return (i != buffer_lookup_table.end())? &buffers[ i->second ] : nullptr;
        }
        kege::RgBufferDesc* findBuffer( const std::string& name )
        {
            auto i = buffer_lookup_table.find( name );
            return (i != buffer_lookup_table.end())? &buffers[ i->second ] : nullptr;
        }

        const kege::RgImageDesc* findImage( const std::string& name )const
        {
            auto i = image_lookup_table.find( name );
            return (i != image_lookup_table.end())? &images[ i->second ] : nullptr;
        }
        kege::RgImageDesc* findImage( const std::string& name )
        {
            auto i = image_lookup_table.find( name );
            return (i != image_lookup_table.end())? &images[ i->second ] : nullptr;
        }

        void insert( const kege::RgRenderPassDesc& desc )
        {
            uint32_t pass_index = uint32_t( passes.size() );
            pass_name_index_table[ desc.name ] = pass_index;
            pass_type_index_table[ desc.pass ] = pass_index;
            passes.push_back( desc );
        }
        void insert( const kege::RgSamplerDesc& desc )
        {
            sampler_lookup_table[ desc.name ] = uint32_t( samplers.size() );
            samplers.push_back( desc );
        }
        void insert( const kege::RgBufferDesc& desc )
        {
            buffer_lookup_table[ desc.name ] = uint32_t( buffers.size() );
            buffers.push_back( desc );
        }
        void insert( const kege::RgImageDesc& desc )
        {
            image_lookup_table[ desc.name ] = uint32_t( images.size() );
            images.push_back( desc );
        }

        std::vector< kege::RgRenderPassDesc > passes;
        std::vector< kege::RgSamplerDesc > samplers;
        std::vector< kege::RgBufferDesc > buffers;
        std::vector< kege::RgImageDesc > images;

        std::unordered_map< kege::RenderPassType, uint32_t > pass_type_index_table;
        std::unordered_map< std::string, uint32_t > pass_name_index_table;
        std::unordered_map< std::string, uint32_t > sampler_lookup_table;
        std::unordered_map< std::string, uint32_t > buffer_lookup_table;
        std::unordered_map< std::string, uint32_t > image_lookup_table;
    };

}
#endif /* render_pass_desc_hpp */
