// Fragment Shader: automatically generated by KEGE based on pipeline key.

#version 450
#extension GL_ARB_separate_shader_objects : enable

#define IN_POSITION 0
#define IN_TEXCOORD 1
#define IN_NORMAL 2
layout(location = IN_POSITION) in vec3 in_position;
layout(location = IN_TEXCOORD) in vec2 in_texcoord;
layout(location = IN_NORMAL) in vec3 in_normal;

#define IN_TANGENT 3
#define IN_BITANGENT 4
layout(location = IN_TANGENT) in vec3 in_tangent;
layout(location = IN_BITANGENT) in vec3 in_bitangent;



#define CAMERA_BINDING 0
// This file defines the camera data uniform buffer for the PBR shader
layout(std140, set = CAMERA_SET, binding = CAMERA_BINDING) uniform CameraData
{
    mat4 view_matrix;
    mat4 projection_matrix;
    mat4 view_projection_matrix;
    vec3 camera_position;
}
camera;

#define OBJECT_BINDING 1
// This defines the uniform buffer for object data in the PBR shader, including the model matrix and normal matrix
layout(std140, set = OBJECT_SET, binding = OBJECT_BINDING) uniform ObjectData
{
    mat4 model_matrix;
    mat4 normal_matrix;
}
object;

#define MATERIAL_SET 2
// This defines the uniform buffer for material properties in the PBR shader
layout(std140, set = MATERIAL_SET, binding = 0) uniform MaterialBuffer
{
    // Base parameters
    vec4 albedo;           // Albedo/diffuse color
    vec3 emissive;

    // PBR Metallic-Roughness parameters
    float metallic;
    float roughness;
    float ambient_occlusion;
    float ior; // Index of refraction

    // Other parameters
    float alpha_cutoff;

    // Subsurface scattering
    vec3  subsurface;
    float subsurface_thickness;

    // Sheen (cloth)
    vec3  sheen;
    float sheen_roughness;

    // Anisotropy
    vec2  anisotropy_direction;
    float anisotropy;

    // UV transforms
    vec4 uv_scale_offset; // xy = scale, zw = offset

    // Transmission
    float transmission;

    // Clear coat (optional)
    float clear_coat;
    float clear_coat_roughness;

    int albedo_map;
    int emissive_map;
    int normal_map;
    int subsurface_map;
    ivec2 metallic_map;
    ivec2 roughness_map;
    ivec2 opacity_map;
    ivec2 ambient_occlusion_map;
    ivec2 sheen_map;
    ivec2 anisotropy_map;
    ivec2 clear_coat_map;
}
material;

// Texture samplers for the material properties
layout(set = MATERIAL_SET, binding = 1) uniform sampler2D MaterialTextures[8];

#define DIRECTIONAL_LIGHT_SET 3
#define DIRECTIONAL_LIGHT_BINDING 4
// This defines the uniform buffer for directional lights in the PBR shader
struct DirectionalLight
{
    vec3  color;
    float intensity;

    vec3 direction;
};
layout(std140, set = DIRECTIONAL_LIGHT_SET, binding = DIRECTIONAL_LIGHT_BINDING) uniform DirectionalLighting
{
    uint directional_light_count;
    DirectionalLight directional_lights[MAX_LIGHTS];
};

#define POINT_LIGHTS_SET 4
#define POINT_LIGHTS_BINDING 5
/**
 * This defines the uniform buffer for point lights in the PBR shader, including
 * the properties of each point light and an array to hold multiple point lights
 */
struct PointLight
{
    vec3  color;
    float intensity;

    vec3  position;
    float point_range;

    float linear_attenuation;
    float quadratic_attenuation;
};
layout(std140, set = POINT_LIGHTS_SET, binding = POINT_LIGHTS_BINDING) uniform PointLightBuffer
{
    uint point_light_count;
    PointLight point_lights[MAX_POINT_LIGHTS];
};

vec3 getAlbedo()
{
    vec3 albedo = material.albedo.rgb;
    // Sample diffuse texture if available
    if (0 <= material.albedo_map) 
    {
        albedo = texture(MaterialTextures[ material.albedo_map ], in_texcoord).rgb;
    }
    return albedo;
}
// Function to decode a normal map value into a world space normal vector
vec3 getNormal()
{
    vec3 world_normal = in_normal;
    if ( 0 <= material.normal_map )
    {
        // Transform from tangent space to world space
        vec3 T = normalize(in_tangent);
        vec3 B = normalize(in_bitangent);
        vec3 N = normalize(in_normal);
        mat3 TBN = mat3(T, B, N);

        // Decode normal from [0,1] to [-1,1]
        vec3 encoded_normal = texture(MaterialTextures[ material.normal_map ], in_texcoord).rgb;
        vec3 tangent_normal = normalize( encoded_normal * 2.0 - 1.0 );

        // Transform to world space
        world_normal = TBN * tangent_normal;
    }
    return world_normal;
}

float getOpacity()
{    
    float opacity = material.albedo.a;
    // Sample opacity texture if available
    if (0 <= material.opacity_map) 
    {
        ivec2 texture_id = material.opacity_map;
        opacity = texture(MaterialTextures[ texture_id.x ], in_texcoord)[ texture_id.y ];
    }
    return opacity;
}
float getAmbientOcclusion()
{    
    float ambient_occlusion = material.ambient_occlusion;
    // Sample ambient occlusion texture if available
    if (0 <= material.ambient_occlusion_map) 
    {
        ivec2 texture_id = material.ambient_occlusion_map;
        ambient_occlusion = texture(MaterialTextures[ texture_id.x ], in_texcoord)[ texture_id.y ];
    }
    return ambient_occlusion;
}
float getRoughness()
{
    float roughness = material.roughness;
    // Sample roughness texture if available
    if (material.roughness_map != 0) 
    {
        ivec2 texture_id = material.roughness_map;
        roughness = texture(MaterialTextures[ texture_id.x ], in_texcoord)[ texture_id.y ];
    }
    return roughness;
}

float getMetallic()
{
    float metallic = material.metallic;
    // Sample metallic texture if available
    if (material.metallic_map != 0) 
    {
        ivec2 texture_id = material.metallic_map;
        metallic = texture(MaterialTextures[ texture_id.x ], in_texcoord)[ texture_id.y ];
    }
    return metallic;
}
vec3 getAlbedo()
{
    vec3 albedo = material.albedo.rgb;
    // Sample diffuse texture if available
    if (0 <= material.albedo_map) 
    {
        albedo = texture(MaterialTextures[ material.albedo_map ], in_texcoord).rgb;
    }
    return albedo;
}

vec3 getEmissive()
{    
    vec3 emissive = material.emissive;
    // Sample emissive texture if available
    if (0 <= material.emissive_map) 
    {
        emissive = texture(MaterialTextures[ material.emissive_map ], in_texcoord).rgb;
    }
    return emissive;
}

// GGX/Trowbridge-Reitz normal distribution function
float distributionGGX(vec3 N, vec3 H, float roughness)
{
    float a = roughness * roughness;
    float a2 = a * a;
    float NdotH = max(dot(N, H), 0.0);
    float NdotH2 = NdotH * NdotH;

    float denom = (NdotH2 * (a2 - 1.0) + 1.0);
    denom = PI * denom * denom;

    return a2 / max(denom, 0.0001);
}

// Smith joint GGX visibility function
float geometrySchlickGGX(float NdotV, float roughness)
{
    float r = (roughness + 1.0);
    float k = (r * r) / 8.0;

    float denom = NdotV * (1.0 - k) + k;
    return NdotV / denom;
}

// Smith's method for combining geometry terms
float geometrySmith(vec3 N, vec3 V, vec3 L, float roughness)
{
    float NdotV = max(dot(N, V), 0.0);
    float NdotL = max(dot(N, L), 0.0);
    float ggx1 = geometrySchlickGGX(NdotV, roughness);
    float ggx2 = geometrySchlickGGX(NdotL, roughness);

    return ggx1 * ggx2;
}

// Fresnel-Schlick approximation
vec3 fresnelSchlick(float cosTheta, vec3 F0)
{
    return F0 + (1.0 - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);
}

// Fresnel-Schlick approximation with roughness
vec3 fresnelSchlickRoughness(float cosTheta, vec3 F0, float roughness)
{
    return F0 + (max(vec3(1.0 - roughness), F0) - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);
}

// ====== MAIN PBR FUNCTION ======
// Calculates PBR lighting for ONE light
vec3 pbrLighting //calculatePBR_Metallic
(
    vec3 N,              // World normal
    vec3 V,              // View direction (world space)
    vec3 L,              // Light direction (world space)
    vec3 light_color,    // Light color/intensity
    vec3 albedo,         // Surface albedo (diffuse color)
    float metallic,      // 0.0 = dielectric, 1.0 = metal
    float roughness,     // 0.0 = smooth, 1.0 = rough
    float ao             // Ambient occlusion
)
{
    // Half vector
    vec3 H = normalize(V + L);

    // Basic dot products
    float NdotV = max(dot(N, V), 0.0);
    float NdotL = max(dot(N, L), 0.0);

    if (NdotL <= 0.0)
    {
        return vec3(0.0);  // Light behind surface
    }

    // Calculate reflectance at normal incidence (F0)
    // For dielectrics: ~0.04, for metals: albedo
    vec3 F0 = mix(vec3(0.04), albedo, metallic);

    // Cook-Torrance BRDF components
    float NDF = distributionGGX(N, H, roughness);
    float G   = geometrySmith(N, V, L, roughness);
    vec3  F   = fresnelSchlick(max(dot(H, V), 0.0), F0);

    // BRDF numerator
    vec3 numerator = NDF * G * F;

    // BRDF denominator
    float denominator = 4.0 * max(NdotV, 0.0) * NdotL;
    vec3 specular = numerator / max(denominator, 0.0001);

    // Diffuse (kD) and specular (kS) factors
    vec3 kS = F;  // Specular contribution
    vec3 kD = vec3(1.0) - kS;

    // Metals have no diffuse reflection
    kD *= 1.0 - metallic;

    // Final lighting
    return (kD * albedo / PI + specular) * light_color * NdotL;
}




void main() {
    vec3 albedo = getAlbedo();

    vec3 normal = getNormal();

    float opacity = getOpacity();

    float ambient_occlusion = getAmbientOcclusion();

    float roughness = getRoughness();

    float metallic = getMetallic();


    vec3 emissive = getEmissive();

    // Integrate the contribution of all directional lights in the scene using the PBR lighting model
    lighting = vec3(0.0);
    for (int i = 0; i < directional_light_count && i < MAX_DIRECTIONAL_LIGHTS; i++)
    {
        lighting += pbrLighting
        (
            normal,
            view,
            light.direction,
            light.color,
            albedo,
            metallic,
            roughness,
            ao
        );
    }
    final_color += lighting;

    // Integrate the contribution of all point lights in the scene using the PBR lighting model
    lighting = vec3(0.0);
    for (int i = 0; i < point_light_count && i < MAX_POINT_LIGHTS; i++)
    {
        Light light = point_lights[i];

        vec3 light_direction = light.position - position;
        float dist = length(direction);
        light_direction /= dist;

        // Calculate attenuation for point and spot lights
        float attenuation = 1.0 / (1.0 + light.linear_attenuation * dist + light.quadratic_attenuation * (dist * dist));

        vec3 radiance = light.color * light.intensity * attenuation;

        lighting += pbrLighting
        (
            normal,
            view,
            light_direction,
            light.color,
            albedo,
            metallic,
            roughness,
            ao
        );
    }
    final_color += lighting;



}
