// Vertex Shader: automatically generated by KEGE based on pipeline key.

#version 450
#extension GL_ARB_separate_shader_objects : enable




void main() {
    // Process vertex based on renderer type

}
